version: '3.4'

services:
 main-api:
  image: ${DOCKER_REGISTRY-}mainapi
  build: 
   context: .
   dockerfile: TweetBook/Dockerfile
  restart: always
  environment:
   - "ConnectionStrings:DefaultConnection=server=localhost;database=Tweetbook;Trusted_Connection=True;MultipleActiveResultSets=true"
  ports:
   - "7000:80"
  depends_on:
   - db-server


 db-server:
  image: mcr.microsoft/mssql-server
  container_name: db-server
  environment:
   - ACCEPT_EULA=Y
  ports:
   - "1400:1433"

